package ring

import (
	"fmt"
	"sync"
)

// Manager provides typed named access to rings (and sync rings), with create/get/resize
// and optional prefill for smoke tests. Internally stores values in maps keyed by name.
//
// NOTE: Go does not allow methods with type parameters on non-generic types.
// Therefore, typed accessors are implemented as standalone generic functions
// (e.g., ring.Get[T](mgr, name)) instead of methods like mgr.Get[T](name).

type Manager struct {
	mu        sync.RWMutex
	rings     map[string]any
	syncRings map[string]any
}

func NewManager() *Manager {
	return &Manager{
		rings:     make(map[string]any),
		syncRings: make(map[string]any),
	}
}

// Get returns an existing typed ring by name.
func Get[T any](m *Manager, name string) (*Ring[T], bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	v, ok := m.rings[name]
	if !ok {
		return nil, false
	}
	r, ok := v.(*Ring[T])
	return r, ok
}

// GetOrCreate returns a ring of the desired capacity.
// If a ring exists with the same capacity, it is returned as-is.
// If capacity differs, the ring is resized preserving the newest min(oldLen, size) elements.
func GetOrCreate[T any](m *Manager, name string, size int) *Ring[T] {
	if size < 1 {
		panic(fmt.Sprintf("manager.GetOrCreate: size must be >= 1, got %d", size))
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	if v, ok := m.rings[name]; ok {
		if r, ok2 := v.(*Ring[T]); ok2 {
			if r.Cap() == size {
				return r
			}
			// Resize: create new ring and copy newest
			return replacePreservingNewest(m, name, r, size)
		}
		// Name exists with a different T. Replace with requested type.
	}
	r := New[T](size)
	m.rings[name] = r
	return r
}

// replacePreservingNewest replaces an existing ring with a new capacity, preserving newest data.
func replacePreservingNewest[T any](m *Manager, name string, old *Ring[T], newSize int) *Ring[T] {
	keep := old.Len()
	if keep > newSize {
		keep = newSize
	}
	nr := New[T](newSize)
	if keep > 0 {
		c1, c2 := old.Newest(keep)
		for _, v := range c1 {
			nr.Push(v)
		}
		for _, v := range c2 {
			nr.Push(v)
		}
	}
	m.rings[name] = nr
	return nr
}

// GetSync returns an existing synchronized ring by name.
func GetSync[T any](m *Manager, name string) (*Sync[T], bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	v, ok := m.syncRings[name]
	if !ok {
		return nil, false
	}
	r, ok := v.(*Sync[T])
	return r, ok
}

// GetOrCreateSync returns a synchronized ring with capacity size.
// Resizes with preservation semantics if capacity differs.
func GetOrCreateSync[T any](m *Manager, name string, size int) *Sync[T] {
	if size < 1 {
		panic(fmt.Sprintf("manager.GetOrCreateSync: size must be >= 1, got %d", size))
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	if v, ok := m.syncRings[name]; ok {
		if sr, ok2 := v.(*Sync[T]); ok2 {
			if sr.Cap() == size {
				return sr
			}
			// resize: extract inner ring safely
			keep := sr.Len()
			if keep > size {
				keep = size
			}
			nr := New[T](size)
			if keep > 0 {
				c1, c2 := sr.Newest(keep)
				for _, v := range c1 {
					nr.Push(v)
				}
				for _, v := range c2 {
					nr.Push(v)
				}
			}
			snew := &Sync[T]{r: nr}
			m.syncRings[name] = snew
			return snew
		}
		// Name exists with a different T. Replace.
	}
	sr := NewSync[T](size)
	m.syncRings[name] = sr
	return sr
}

// Prefill clears/creates the ring and pushes size samples generated by gen(i) for i=0..size-1.
// Returns the ring. Implemented as a standalone generic function for the same reason as above.
func Prefill[T any](m *Manager, name string, size int, gen func(i int) T) *Ring[T] {
	r := GetOrCreate[T](m, name, size)
	r.Clear()
	for i := 0; i < size; i++ {
		r.Push(gen(i))
	}
	return r
}
