// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tychoCpuBinCounters struct {
	IdleNs    uint64
	IrqNs     uint64
	SoftirqNs uint64
}

type tychoCpuStateT struct {
	LastTs         uint64
	CurrentPid     uint32
	_              [4]byte
	IdleNs         uint64
	IrqNs          uint64
	SoftirqNs      uint64
	IrqEntryTs     uint64
	SoftirqEntryTs uint64
}

type tychoProcessMetricsT struct {
	CgroupId       uint64
	Pid            uint64
	IsKthread      uint8
	Pad            [7]uint8
	ProcessRunTime uint64
	CpuCycles      uint64
	CpuInstr       uint64
	CacheMiss      uint64
	PageCacheHit   uint64
	VecNr          [10]uint16
	Comm           [16]int8
	_              [4]byte
}

// loadTycho returns the embedded CollectionSpec for tycho.
func loadTycho() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TychoBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tycho: %w", err)
	}

	return spec, err
}

// loadTychoObjects loads tycho and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tychoObjects
//	*tychoPrograms
//	*tychoMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTychoObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTycho()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tychoSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tychoSpecs struct {
	tychoProgramSpecs
	tychoMapSpecs
}

// tychoSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tychoProgramSpecs struct {
	KeplerIrqEntry         *ebpf.ProgramSpec `ebpf:"kepler_irq_entry"`
	KeplerIrqExit          *ebpf.ProgramSpec `ebpf:"kepler_irq_exit"`
	KeplerReadPageTrace    *ebpf.ProgramSpec `ebpf:"kepler_read_page_trace"`
	KeplerSchedSwitchTrace *ebpf.ProgramSpec `ebpf:"kepler_sched_switch_trace"`
	KeplerSoftirqEntry     *ebpf.ProgramSpec `ebpf:"kepler_softirq_entry"`
	KeplerSoftirqExit      *ebpf.ProgramSpec `ebpf:"kepler_softirq_exit"`
	KeplerWritePageTrace   *ebpf.ProgramSpec `ebpf:"kepler_write_page_trace"`
}

// tychoMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tychoMapSpecs struct {
	CacheMiss                  *ebpf.MapSpec `ebpf:"cache_miss"`
	CacheMissEventReader       *ebpf.MapSpec `ebpf:"cache_miss_event_reader"`
	CpuBins                    *ebpf.MapSpec `ebpf:"cpu_bins"`
	CpuCycles                  *ebpf.MapSpec `ebpf:"cpu_cycles"`
	CpuCyclesEventReader       *ebpf.MapSpec `ebpf:"cpu_cycles_event_reader"`
	CpuInstructions            *ebpf.MapSpec `ebpf:"cpu_instructions"`
	CpuInstructionsEventReader *ebpf.MapSpec `ebpf:"cpu_instructions_event_reader"`
	CpuStates                  *ebpf.MapSpec `ebpf:"cpu_states"`
	PidTimeMap                 *ebpf.MapSpec `ebpf:"pid_time_map"`
	Processes                  *ebpf.MapSpec `ebpf:"processes"`
}

// tychoObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTychoObjects or ebpf.CollectionSpec.LoadAndAssign.
type tychoObjects struct {
	tychoPrograms
	tychoMaps
}

func (o *tychoObjects) Close() error {
	return _TychoClose(
		&o.tychoPrograms,
		&o.tychoMaps,
	)
}

// tychoMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTychoObjects or ebpf.CollectionSpec.LoadAndAssign.
type tychoMaps struct {
	CacheMiss                  *ebpf.Map `ebpf:"cache_miss"`
	CacheMissEventReader       *ebpf.Map `ebpf:"cache_miss_event_reader"`
	CpuBins                    *ebpf.Map `ebpf:"cpu_bins"`
	CpuCycles                  *ebpf.Map `ebpf:"cpu_cycles"`
	CpuCyclesEventReader       *ebpf.Map `ebpf:"cpu_cycles_event_reader"`
	CpuInstructions            *ebpf.Map `ebpf:"cpu_instructions"`
	CpuInstructionsEventReader *ebpf.Map `ebpf:"cpu_instructions_event_reader"`
	CpuStates                  *ebpf.Map `ebpf:"cpu_states"`
	PidTimeMap                 *ebpf.Map `ebpf:"pid_time_map"`
	Processes                  *ebpf.Map `ebpf:"processes"`
}

func (m *tychoMaps) Close() error {
	return _TychoClose(
		m.CacheMiss,
		m.CacheMissEventReader,
		m.CpuBins,
		m.CpuCycles,
		m.CpuCyclesEventReader,
		m.CpuInstructions,
		m.CpuInstructionsEventReader,
		m.CpuStates,
		m.PidTimeMap,
		m.Processes,
	)
}

// tychoPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTychoObjects or ebpf.CollectionSpec.LoadAndAssign.
type tychoPrograms struct {
	KeplerIrqEntry         *ebpf.Program `ebpf:"kepler_irq_entry"`
	KeplerIrqExit          *ebpf.Program `ebpf:"kepler_irq_exit"`
	KeplerReadPageTrace    *ebpf.Program `ebpf:"kepler_read_page_trace"`
	KeplerSchedSwitchTrace *ebpf.Program `ebpf:"kepler_sched_switch_trace"`
	KeplerSoftirqEntry     *ebpf.Program `ebpf:"kepler_softirq_entry"`
	KeplerSoftirqExit      *ebpf.Program `ebpf:"kepler_softirq_exit"`
	KeplerWritePageTrace   *ebpf.Program `ebpf:"kepler_write_page_trace"`
}

func (p *tychoPrograms) Close() error {
	return _TychoClose(
		p.KeplerIrqEntry,
		p.KeplerIrqExit,
		p.KeplerReadPageTrace,
		p.KeplerSchedSwitchTrace,
		p.KeplerSoftirqEntry,
		p.KeplerSoftirqExit,
		p.KeplerWritePageTrace,
	)
}

func _TychoClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tycho_bpfel.o
var _TychoBytes []byte
