name: yamllint

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: read-all

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: yamllint
        run: yamllint -c .yamllint.yaml --strict .
